openapi: 3.1.0
info:
  title: FKSDB api
  summary: GET api for data stored in FKSDB
  version: 0.0.1
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
servers:
  - url: http://db.fykos.local/api/
paths:
  /event:
    get: { }
  /event/{eventId}:
    get: { }
  /event/{eventId}/team:
    get: { }
  /event/{eventId}/participant:
    get: { }
  /contest:
    get: { }
  /contest/{contstId}/organizer:
    get: { }
  /contest/{contstId}/year/{year}/stats:
    get: { }
