name: PHPStan

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php }} with ${{ matrix.database }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4' , '8.0' , '8.1' ]
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpstan@v3
      with:
        path: app/ tests/ tests/
