name: PHP (Nette Tester)

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [ '7.4' ]
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: recursive
      - uses: shivammathur/setup-php@v2
        name: Setup PHP
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, mysql, soap, sqlite3, xml
          tools: composer
          ini-values: session.gc_probability=0, date.timezone="Europe/Prague", display_startup_errors = Off
      - name: Composer install
        run: composer install --no-progress --prefer-dist
      - name: FKSDB configuration
        run: "sed -e 's/user:/user: root/' app/config/config.local.neon.sample > app/config/config.local.neon"
      - name: i18n compile
        run: |
          sudo apt-get install gettext
          ./i18n/compile.sh
      - name: Start MySQL
        run: |
          sudo service mysql start
          sudo mysql -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY ''; CREATE USER 'runner'@'localhost' IDENTIFIED BY ''; GRANT ALL PRIVILEGES ON * . * TO 'runner'@'localhost'; FLUSH PRIVILEGES;"
      - run: composer run-script initTestDatabase
        name: Init test database
      - run: composer run-script test
        name: Test
      - if: failure()
        name: Failure output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: tests/**/*.actual
